version: '3'

services:
  app:
    container_name: /python-docker
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/python-docker
    network_mode: host

  web:
    container_name: /mynginx1
    image: mynginx1
    ports:
      - "80:80"
    network_mode: host
